### ISSUE TITLE
Example of 3D plot with colored blocks

### ISSUE THREAD

**Issue by juliohm** [j-fu/PlutoVista.jl#8]
Suppose you have a random set of 3D blocks:

```julia
grid = CartesianGrid(100, 100, 100)

blocks = sample(grid, UniformSampling(1000))

blocks[1] # access first block (or hexahedron)
```

Can we use this package to create a visualization in Pluto where each block is colored according to a given variable?

**Comment by j-fu** [comment]
Hi, this sounds like volume rendering.  If so, this is currently not supported. The vtk.js backend certainly [has this possibility](https://kitware.github.io/vtk-js/examples/VolumeViewer/VolumeViewer.html?fileURL=https://data.kitware.com/api/v1/item/59e12e988d777f31ac6455c5/download), so there would be a way to add this. May be DashVTK.jl can help here (but AFAIU not in a pluto notebook). 

What this package can do is that you can interpolate your data onto the nodes of the hexahedra. These you can pass to the package, then you can visualize different transparent isosurface levels. For more or less smooth functions this is a good alternative to volume rendering.

**Comment by juliohm** [comment]
Maybe it is not volume rendering, just a scatter plot of repeated meshes with different color. That is what I do with Makie in MeshViz.jl, I simply create a prototype hexahedron and copy it all over the place with scattermesh

**Comment by j-fu** [comment]
Can you send me a screenshot? - Maybe I just misunderstood you.

**Comment by juliohm** [comment]
I am far from my work station, but the following code should do it:

```julia
using Meshes
using MeshViz

import GLMakie as Mke

grid = CartesianGrid(100, 100, 100)

blocks = sample(grid, UniformSampling(1000))

viz(blocks, color=1:1000)
```

**Comment by j-fu** [comment]
Hi, I tried it out, well, through some hoops it might be possible by supplying all cube surfaces in triangulated form with a boundary region number for each cube and a corresponding color scale for the boundary (may be this would need some fixes). 
No interior tets needed (not sure if this works in the moment, but that could be rather easily fixed).

**Comment by juliohm** [comment]
Closing the issue as not relevant in the near future.
